In [5]:
import pandas as pd
import glob
from sqlalchemy import create_engine

# Path to folder containing files
path = r"C:\_SDATA\__Pers\Courses\20250521_NTUC_Associate_Data_Analyst\Capstone Project -Retail Business analysis\Dataset\Files\*.csv"

# Get all file names
files = glob.glob(path)

# Read and append
df = pd.concat([pd.read_csv(f) for f in files], ignore_index=True)

In [6]:
df.head()

,name,main_category,sub_category,image,link,ratings,no_of_ratings,discount_price,actual_price,Unnamed: 0
0,Lloyd 1.5 Ton 3 Star Inverter Split Ac (5 In 1...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/31UISB90sY...,https://www.amazon.in/Lloyd-Inverter-Convertib...,4.2,"2,255","₹32,999","₹58,990",NaN
1,LG 1.5 Ton 5 Star AI DUAL Inverter Split AC (C...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/51JFb7FctD...,https://www.amazon.in/LG-Convertible-Anti-Viru...,4.2,"2,948","₹46,490","₹75,990",NaN
2,LG 1 Ton 4 Star Ai Dual Inverter Split Ac (Cop...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/51JFb7FctD...,https://www.amazon.in/LG-Inverter-Convertible-...,4.2,"1,206","₹34,490","₹61,990",NaN
3,LG 1.5 Ton 3 Star AI DUAL Inverter Split AC (C...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/51JFb7FctD...,https://www.amazon.in/LG-Convertible-Anti-Viru...,4.0,69,"₹37,990","₹68,990",NaN
4,Carrier 1.5 Ton 3 Star Inverter Split AC (Copp...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/41lrtqXPiW...,https://www.amazon.in/Carrier-Inverter-Split-C...,4.1,630,"₹34,490","₹67,790",NaN

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1093570 entries, 0 to 1093569
Data columns (total 10 columns):
 #   Column          Non-Null Count    Dtype
---  ------          --------------    -----
 0   name            1093570 non-null  object
 1   main_category   1093570 non-null  object
 2   sub_category    1093570 non-null  object
 3   image           1093570 non-null  object
 4   link            1093570 non-null  object
 5   ratings         742077 non-null   object
 6   no_of_ratings   742077 non-null   object
 7   discount_price  971728 non-null   object
 8   actual_price    1058014 non-null  object
 9   Unnamed: 0      551585 non-null   float64
dtypes: float64(1), object(9)
memory usage: 83.4+ MB

In [8]:
df['discount_price'] = pd.to_numeric(
    df['discount_price'].astype(str).str.replace('[^0-9.]', '', regex=True),
    errors='coerce'
)

In [9]:
df['actual_price'] = pd.to_numeric(
    df['actual_price'].astype(str).str.replace('[^0-9.]', '', regex=True),
    errors='coerce'
)

In [10]:
df['ratings'] = pd.to_numeric(
    df['ratings'],
    errors='coerce'
)

df = df[df['ratings'].between(0, 5)]

In [11]:
df['no_of_ratings'] = pd.to_numeric(df['no_of_ratings'], errors='coerce')

In [12]:
threshold = df['actual_price'].quantile(0.95)

df['actual_price'] = df['actual_price'].apply(
    lambda x: x / 100 if x > threshold else x
)

df['discount_price'] = df['discount_price'].apply(
    lambda x: x / 100 if x > threshold else x
)

In [13]:
df.describe()

,ratings,no_of_ratings,discount_price,actual_price,Unnamed: 0
count,729635.000000,673565.000000,660924.000000,7.161830e+05,369558.000000
mean,3.829124,87.458676,1042.080506,2.229195e+03,6078.597081
std,0.759261,170.046463,1400.842267,1.654496e+05,5376.316935
min,1.000000,1.000000,8.000000,0.000000e+00,0.000000
25%,3.500000,4.000000,349.000000,7.590000e+02,1174.000000
50%,3.900000,15.000000,580.000000,1.299000e+03,4749.000000
75%,4.300000,77.000000,1084.000000,2.499000e+03,9480.000000
max,5.000000,999.000000,12499.900000,9.900000e+07,19199.000000

In [14]:
df.drop(columns=['Unnamed: 0'], inplace=True)

In [15]:
df.describe(include = 'all')

,name,main_category,sub_category,image,link,ratings,no_of_ratings,discount_price,actual_price
count,729635,729635,729635,729635,729635,729635.000000,673565.000000,660924.000000,7.161830e+05
unique,263539,20,112,320680,369558,NaN,NaN,NaN,NaN
top,Red Tape Men's Walking Shoes,accessories,Clothing,https://m.media-amazon.com/images/I/61ijir6ozP...,https://www.amazon.in/Mothercare-Carrot-Regula...,NaN,NaN,NaN,NaN
freq,488,134838,35448,200,2,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,3.829124,87.458676,1042.080506,2.229195e+03
std,NaN,NaN,NaN,NaN,NaN,0.759261,170.046463,1400.842267,1.654496e+05
min,NaN,NaN,NaN,NaN,NaN,1.000000,1.000000,8.000000,0.000000e+00
25%,NaN,NaN,NaN,NaN,NaN,3.500000,4.000000,349.000000,7.590000e+02
50%,NaN,NaN,NaN,NaN,NaN,3.900000,15.000000,580.000000,1.299000e+03
75%,NaN,NaN,NaN,NaN,NaN,4.300000,77.000000,1084.000000,2.499000e+03
max,NaN,NaN,NaN,NaN,NaN,5.000000,999.000000,12499.900000,9.900000e+07

In [16]:
df.isnull().sum()

name                  0
main_category         0
sub_category          0
image                 0
link                  0
ratings               0
no_of_ratings     56070
discount_price    68711
actual_price      13452
dtype: int64

In [17]:
df['no_of_ratings'] = df['no_of_ratings'].fillna(
    df.groupby(['main_category', 'sub_category'])
        ['no_of_ratings'].transform('median').round()).astype('Int64')

In [18]:
df.head()

,name,main_category,sub_category,image,link,ratings,no_of_ratings,discount_price,actual_price
0,Lloyd 1.5 Ton 3 Star Inverter Split Ac (5 In 1...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/31UISB90sY...,https://www.amazon.in/Lloyd-Inverter-Convertib...,4.2,16,329.99,589.9
1,LG 1.5 Ton 5 Star AI DUAL Inverter Split AC (C...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/51JFb7FctD...,https://www.amazon.in/LG-Convertible-Anti-Viru...,4.2,16,464.90,759.9
2,LG 1 Ton 4 Star Ai Dual Inverter Split Ac (Cop...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/51JFb7FctD...,https://www.amazon.in/LG-Inverter-Convertible-...,4.2,16,344.90,619.9
3,LG 1.5 Ton 3 Star AI DUAL Inverter Split AC (C...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/51JFb7FctD...,https://www.amazon.in/LG-Convertible-Anti-Viru...,4.0,69,379.90,689.9
4,Carrier 1.5 Ton 3 Star Inverter Split AC (Copp...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/41lrtqXPiW...,https://www.amazon.in/Carrier-Inverter-Split-C...,4.1,630,344.90,677.9

In [19]:
df.drop(columns=['image', 'link'],inplace=True )

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 729635 entries, 0 to 1093569
Data columns (total 7 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   name            729635 non-null  object
 1   main_category   729635 non-null  object
 2   sub_category    729635 non-null  object
 3   ratings         729635 non-null  float64
 4   no_of_ratings   729635 non-null  Int64
 5   discount_price  660924 non-null  float64
 6   actual_price    716183 non-null  float64
dtypes: Int64(1), float64(3), object(3)
memory usage: 45.2+ MB

In [21]:
df.isnull().sum()

name                  0
main_category         0
sub_category          0
ratings               0
no_of_ratings         0
discount_price    68711
actual_price      13452
dtype: int64

In [22]:
before = len(df)
df.dropna(subset=['actual_price', 'discount_price'], inplace=True)
after = len(df)

print(f"Rows removed: {before - after}")

Rows removed: 68711

In [23]:
df.isnull().sum()

name              0
main_category     0
sub_category      0
ratings           0
no_of_ratings     0
discount_price    0
actual_price      0
dtype: int64

In [24]:
pip install pandas sqlalchemy pyodbc

Requirement already satisfied: pandas in c:\users\sheeb\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: sqlalchemy in c:\users\sheeb\anaconda3\lib\site-packages (2.0.39)
Requirement already satisfied: pyodbc in c:\users\sheeb\anaconda3\lib\site-packages (5.2.0)
Requirement already satisfied: numpy>=1.26.0 in c:\users\sheeb\anaconda3\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\sheeb\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\sheeb\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\sheeb\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\sheeb\anaconda3\lib\site-packages (from sqlalchemy) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\sheeb\appdata\roaming\python\python313\site-packages (from sqlalchemy) (4.14.0)
Requirement already satisfied: six>=1.5 in c:\users\sheeb\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [25]:
engine = create_engine(
    "mssql+pyodbc://LAPTOP-4AC7M277\SQLEXPRESS01/Retail_Business?"
    "driver=ODBC+Driver+17+for+SQL+Server&trusted_connection=yes"
)

In [26]:
df.to_sql(
    name='Products',        # Table name in SQL
    con=engine,
    if_exists='replace',     # 'append' | 'replace' | 'fail'
    index=False
)

134